Added Maven Dependency Check GitLab format conversion to JUNIT
logchange/SecScanner2JUnit pull request #45
Opened 2024-04-10 17:08 UTC by marwin1991

Closes #43

2024-04-15 08:15 UTC, marwin1991 commented
@angrymeir Will you find some time or should I merge it?

2024-04-17 14:50 UTC, marwin1991 commented
@angrymeir friendly ping :)

2024-04-17 15:19 UTC, angrymeir requested changes
Sorry, I was busy for the last two weeks..
Looks good as always! But please rename `test_test_container_scanning.py` into `test_maven_dependency_check.py` :)

2024-04-22 11:51 UTC, marwin1991 commented
> test_maven_dependency_check.py

@angrymeir no problem :)

thank you for your time!

2024-05-07 15:43 UTC, marwin1991 commented
@angrymeir ping :)

2024-05-19 11:32 UTC, marwin1991 commented
@angrymeir friendly ping :)

2024-05-29 11:55 UTC, angrymeir submitted a review, later dismissed
OMG! I'm sorry, I completely forgot...
My apologies 🙏🏼

2024-05-29 11:59 UTC, angrymeir commented
Please feel free to merge whenever you want!

2025-02-08 13:51 UTC, merged